name: Challenge
version: '${project.version}'
main: com.aquafun3d.challenge.Main
api-version: 1.17
authors: [ AquaFun3D ]
description: Minecraft Challenge Plugin in Kotlin
website: AquaFun3D.com

commands:
  timer:
    description: Toggles the timer
  Damage:
    description: Toggles damage visibilty
    aliases: [dmg]