name: Challenge
version: '${project.version}'
main: com.aquafun3d.challenge.Main
api-version: 1.18
authors: [ AquaFun3D ]
description: Minecraft Challenge Plugin in Kotlin
website: AquaFun3D.com

commands:
  timer:
    description: Toggles the timer
  damage:
    description: Toggles damage visibilty
    aliases: [dmg]
  waypoint:
    description: sets or show waypoints
    aliases: [wp]
  settings:
    description: define rules of the challenge
  start:
    description: starts the challenge